email: kanghyk@gmail.com
author: kanghyki

title: Kanghyki
baseurl: ""
description: >
    블로그
url: "https://kanghyki.github.io"

github:
  username: kanghyki
  blame: "https://github.com/kanghyki/kanghyki.github.io/blame/main/_wiki"
  history: "https://github.com/kanghyki/kanghyki.github.io/commits/main/_wiki"
  issue: "https://github.com/kanghyki/kanghyki.github.io/issues/new"
  edit: "https://github.com/kanghyki/kanghyki.github.io/edit/main/_wiki"

giscus:
  repo: kanghyki/kanghyki.github.io
  repo_id: R_kgDOMu3cnQ
  category: Comments
  category_id: DIC_kwDOMu3cnc4CiZVC

# Build settings
plugins:
  - jekyll-feed

collections:
    wiki:
        output: true
        permalink: /:collection/:path/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
