email: kanghyk@gmail.com
author: kanghyki

title: Kanghyki
baseurl: ""
description: >
    블로그
url: "https://kanghyki.github.io"
github_username:  kanghyki

# Build settings
plugins:
  - jekyll-feed

collections:
    wiki:
        output: true
        permalink: /:collection/:path/

markdown: kramdown

blame: "https://github.com/kanghyki/kanghyki.github.io/blame/main/_wiki"
history: "https://github.com/kanghyki/kanghyki.github.io/commits/main/_wiki"
