email: kanghyk@gmail.com
author: kanghyki

title: kanghyki
baseurl: ""
description: A wiki documenting what I learn and experiment with.
profile_image: "https://avatars.githubusercontent.com/u/94736461?v=4"
profile_bio: |
  Hello! I’m kanghyki.
  I document what I’ve learned, what I’ve experimented with, and even the things I don’t fully understand yet.
  Sometimes, I also post whatever comes to mind.
url: "https://kanghyki.github.io"
timezone: Asia/Seoul
github:
  username: kanghyki
  blame: "https://github.com/kanghyki/kanghyki.github.io/blame/main/_notes"
  history: "https://github.com/kanghyki/kanghyki.github.io/commits/main/_notes"
  issue: "https://github.com/kanghyki/kanghyki.github.io/issues/new"
  edit: "https://github.com/kanghyki/kanghyki.github.io/edit/main/_notes"

giscus:
  repo: kanghyki/kanghyki.github.io
  repo_id: R_kgDOQ-eBbQ
  category: Announcements
  category_id: DIC_kwDOQ-eBbc4C1P6j

# Build settings
plugins:
  - jekyll-feed

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "wiki"
      latex: true

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "STRIKETHROUGH_DOUBLE_TILDE", "HARDBREAKS", "GITHUB_PRE_LANG"]
  extensions: ["table", "strikethrough", "autolink", "tasklist"]

exclude:
  - scripts
  - _notes/Templates

include:
  - _notes/assets
  - data
